export const ADD_TODO = "ADD_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER"
export const SET_TEXT = "SET_TEXT"
export const SET_THEME = "SET_THEME"
export const DELETE_TODO = "DELETE_TODO"